BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `teste` (
	`id`	INTEGER,
	`num`	INTEGER,
	PRIMARY KEY(`id`)
);
INSERT INTO `teste` VALUES (1,2);
INSERT INTO `teste` VALUES (2,3);
INSERT INTO `teste` VALUES (3,2);
INSERT INTO `teste` VALUES (4,NULL);
INSERT INTO `teste` VALUES (5,NULL);
COMMIT;
